name: Release

# when tag '*.*.*.*' is pushed
on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  check-tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check tag name
        run: test `echo '${{ github.ref }}' | cut -d '/' -f 3` = `grep 'TAG :=' Makefile | cut -d ' ' -f 3`

  release:
    needs: check-tag-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: make build

      - name: Save the Docker image
        run: make save

      - name: Zip release asset
        run: |
          tag_name=`grep 'TAG :=' Makefile | cut -d ' ' -f 3`
          gzip rockylinux_minecraft_server_$tag_name.tar

      - name: Create Release
        run: |
          tag_name=`grep 'TAG :=' Makefile | cut -d ' ' -f 3`
          echo "{ \"tag_name\": \"$tag_name\", \"prerelease\": true, \"body\": \"Test Release\" }" > ./request_body
          curl \
          $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d @request_body \
          > ./response_body
          cat response_body
